backend:
  name: github
  repo: sergiofornet/gatsby-hello-world

# media_folder: static/assets
media_library:
  name: cloudinary
  config:
    cloud_name: dnuawhhqp
    api_key: '753688193199724'
# public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: 'thumbnail',
          label: 'Featured Image',
          widget: 'image',
        }
      - name: 'gallery'
        label: 'Gallery'
        widget: 'list'
        summary: '{{fields.image}} - {{fields.imageresponsive}}'
        fields:
          - { name: image, label: Image, widget: image }
          - { name: imageresponsive, label: Image2x, widget: image }
